var search = [
    {
      'keys': ['알아두기', 'Java와 JavaScript는 서로 다른 언어입니다.', '순수 자바스크립트', 'Rhino', 'JavaScript 엔진', 'iOS', '안드로이드 버전', '안드로이드 버전 5.0(롤리팝) 미만'],
      'location': '1-1'
    }, {
      'keys': ['카카오톡 봇', '자동으로 응답', '메신저봇R을 기준', '채팅 자동응답 봇'],
      'location': '1-2'
    }, {
      'keys': ['작동 원리', '메신저봇', 'NotificationListenerService', 'WearableExtender', 'Rhino JavaScript Engine', '알림 정보를 전달'],
      'location': '1-3'
    }, {
      'keys': ['개발 준비', '앱 설치', '부계정을 사용할 경우', 'Google Play', 'Wear OS by Google', 'Android Wear', '안드로이드 버전이 7.0', '앱을 추가로 설치', '구동할 수 있는 환경이 조성', '알림 읽기 권한이 없습니다.', '데이터 폴더', '변경을 선택해 저장할 경로를 지정합니다.', '메신저봇R의 메인 화면', '스크립트 추가 버튼', '새 봇 창', '스크립트 이름', '올바른 추가 설정', '본계정과 부계정 모두', '삼성 듀얼 메신저 기능을 사용할 경우', '복제 앱을 사용할 경우', '공용 설정 > 알림을 읽을 패키지명', 'if(packageName != \'복제된 앱의 패키지명\') return;'],
      'location': '1-4'
    }, {
      'keys': [],
      'location': '1-5'
    }, {
      'keys': [],
      'location': '1-6'
    }, {
      'keys': [],
      'location': '1-7'
    }, {
      'keys': [],
      'location': '2-1'
    }, {
      'keys': [],
      'location': '2-2'
    }, {
      'keys': [],
      'location': '2-3'
    }, {
      'keys': [],
      'location': '2-4'
    }, {
      'keys': [],
      'location': '2-5'
    }, {
      'keys': [],
      'location': '2-6'
    }, {
      'keys': [],
      'location': '2-7'
    }, {
      'keys': [],
      'location': '2-8'
    }, {
      'keys': [],
      'location': '2-9'
    }, {
      'keys': [],
      'location': '2-10'
    }, {
      'keys': [],
      'location': '3-1'
    }, {
      'keys': [],
      'location': '3-2'
    }, {
      'keys': [],
      'location': '3-3'
    }, {
      'keys': [],
      'location': '3-4'
    }, {
      'keys': [],
      'location': '3-5'
    }, {
      'keys': [],
      'location': '3-6'
    }, {
      'keys': [],
      'location': '3-7'
    }, {
      'keys': [],
      'location': '3-8'
    }, {
      'keys': [],
      'location': '3-9'
    }, {
      'keys': [],
      'location': '4-1'
    }, {
      'keys': [],
      'location': '4-2'
    }, {
      'keys': [],
      'location': '4-3'
    }, {
      'keys': [],
      'location': '4-4'
    }, {
      'keys': [],
      'location': '4-5'
    }, {
      'keys': [],
      'location': '4-6'
    }, {
      'keys': [],
      'location': '4-7'
    }, {
      'keys': [],
      'location': '4-8'
    }, {
      'keys': [],
      'location': '4-9'
    }, {
      'keys': [],
      'location': '4-11'
    }, {
      'keys': [],
      'location': '4-11'
    }, {
      'keys': [],
      'location': '4-12'
    }, {
      'keys': [],
      'location': '5-1'
    }, {
      'keys': [],
      'location': '5-2'
    }, {
      'keys': [],
      'location': '5-3'
    }, {
      'keys': [],
      'location': '5-4'
    }, {
      'keys': [],
      'location': '5-5'
    }, {
      'keys': [],
      'location': '6-1'
    }, {
      'keys': [],
      'location': '6-2'
    }, {
      'keys': [],
      'location': '6-3'
    }
  ];